### ISSUE TITLE
The 'more' link breaks onto two lines between 768px and 769px

### ISSUE THREAD

**Issue by barrymcgee** [canonical-webteam/global-nav#14]
This screenshot is at 769px

<img width="767" alt="screen shot 2017-04-27 at 10 49 41" src="https://cloud.githubusercontent.com/assets/505570/25477966/435210aa-2b37-11e7-930a-0cd6155ee661.png">

**Comment by anthonydillon** [comment]
I think this is just the global navigation on ubuntu.com but this project does need to be responsive. Therefore will leave this as the responsive feature to this project.

**Comment by anthonydillon** [comment]
https://github.com/ubuntudesign/www.ubuntu.com-design/issues/1
