### ISSUE TITLE
Make global-nav an NPM package

### ISSUE THREAD

**Issue by nottrobin** [canonical-webteam/global-nav#33]
And change the README to suggest installing via NPM.

This is because (as far as I remember) we agreed to no longer use Bower packages.

**Comment by deadlight** [comment]
@anthonydillon has already completed this:
 - NPM package: https://github.com/canonical-websites/design.ubuntu.com/pull/101/files
 - Implementation on design.ubuntu.com: https://github.com/canonical-websites/design.ubuntu.com/pull/101/files
