### ISSUE TITLE
Investigate other methods of building HTML elements with JS

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-webteam/global-nav#41]
At the moment, the global-nav builds a huge amount of markup from strings using a simple string-to-HTML-element helper function. We should investigate better methods of building HTML elements with JS, because at the moment it feels a little bit hacky.

Options include:
- Javascript templates
- JSX (without React)
- Web components

**Comment by tbille** [comment]
Duplicate canonical-webteam/global-nav#55
