### ISSUE TITLE
Copy updates to global nav - build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-webteam/global-nav#45]
Close up space between logos and texts. (mark request)
Include Canonical as a site. (Carla request)
Resources links need some consideration.
See anoted screen shot attached.
links to certification

Copydoc: https://docs.google.com/document/d/1fmPEv9gi4kZZDDylGtUJg5KNwK7GktdMTYCF570WyYA/edit#heading=h.s107xu2kx7vo

**Comment by anthonydillon** [comment]
Completed via https://github.com/canonical-websites/www.ubuntu.com/issues/4051
