### ISSUE TITLE
Make "login" section optional

### ISSUE THREAD

**Issue by nottrobin** [canonical-webteam/global-nav#59]
The "login" section in the global nav is problematic - it doesn't do what you expect, effectively duplicates content from "products", and makes it difficult to put the global nav on sites with their own login, like snapcraft.io.

I believe the simplest solution is to simply remove it as I don't think it adds anything.

Could we do this?

**Comment by nottrobin** [comment]
@pmahnke okay I've renamed this issue to 'make "login" section optional', which seems the simplest first step.

**Comment by hatched** [comment]
JAAS and the Juju GUI also both have a top right nav link/dropdown. Optional works for me :-)

**Comment by therealjuan** [comment]
We also need to make the login optional on snapcraft.io. This will helps to include Products on the global navigation.

**Comment by clagom** [comment]
We discussed this with Carla too, an optional login for the Canonical Global Nav when there's a login on the website itself already seems reasonable until we have a real unique global login implemented.

**Comment by carlaberkers** [comment]
Yes, I'd like to do some UX work on the global nav with the objectives of
1. Making the nav + login on Ubuntu.com useful and usable
2. Figuring out how login on sites with a specific login (like JAAS / Snapcraft) will work when the global nav is applied
3. Figuring out what would be required to unify different logins (aware this is very complex and not something we can do any time soon, but maybe some logins can be merged)
