### ISSUE TITLE
Small screen positioning on the bottom doesn't work with sticky footer

### ISSUE THREAD

**Issue by bartaz** [canonical-webteam/global-nav#62]
Global nav on small screens currently positions itself on the bottom of the page using absolute positioning.

It's a tricky thing by itself, as it requires additional margin on the bottom and assumes no other styles on body will affect it.

One of the things that does affect it is a sticky footer. Snapcraft.io uses one, Vanilla has it as utility (`vf-u-sticky-footer`). They set `html` and `body` height to 100% (to make sticky footer work) and this causes global nav to appear in the bottom of the browser screen rather bottom of the page. And global nav (absolutely positioned) keeps it's position when scrolled making it appear in the middle of the page.

<img width="649" alt="screen shot 2018-12-14 at 12 01 46" src="https://user-images.githubusercontent.com/83575/50003709-f1212200-ffa4-11e8-8058-54e993e8d394.png">

Discovered when QAing https://github.com/canonical-websites/snapcraft.io/pull/1449

**Comment by bartaz** [comment]
Because global nav is injected by JS, maybe it would be possible to inject it to the end of body on small screens (and move it to top of body in DOM on bigger screens) rather then relying on CSS and absolute positioning?

**Comment by nottrobin** [comment]
One benefit of doing it in CSS is that we don't have to add a JavaScript listener for the screen resize event. This can be a pretty resource-intensive event to listen for. It would be very nice to have a CSS-only solution.

**Comment by bartaz** [comment]
I agree that it would be ideal to have CSS only solution. But I don't know the solution that would work in all cases (when body styles are not default).

Only thing that comes to mind would be CSS grid that maybe could do that - but that probably assumes that sites using global-nav would need to use CSS grid for layout. Not sure if global-nav itself can just use it.

**Comment by anthonydillon** [comment]
Off the top of my head the solution could be changing the sticky footer styling from setting the body from `height: 100%;` to `min-height: 100vh`. Not tested thought

**Comment by bartaz** [comment]
@anthonydillon Tried `min-height: 100%` and it didn't do it, but `100vh` works like a charm! Need to learn more about these units.

<img width="1225" alt="screen shot 2018-12-14 at 15 54 56" src="https://user-images.githubusercontent.com/83575/50010039-b75a1680-ffb8-11e8-9f7d-917cc8ea2989.png">

**Comment by bartaz** [comment]
Also addressed on snapcraft.io part: https://github.com/canonical-websites/snapcraft.io/pull/1449
