### ISSUE TITLE
We should move this package on npm under @canonical scope

### ISSUE THREAD

**Issue by barrymcgee** [canonical-webteam/global-nav#89]
This package is totally specific to Canonical - we should move it under the [@canonical org scope](https://www.npmjs.com/org/canonical) on npm asap.

https://stackoverflow.com/questions/43007471/how-to-migrate-npm-package-to-an-organization-scope

Note: you will need to [deprecate the old package](https://docs.npmjs.com/cli/deprecate) at 'global-nav' namespace and point to the new one.

**Comment by barrymcgee** [comment]
@hatched Can you grant me access to the Canonical org on npm please?

**Comment by hatched** [comment]
I've moved this to https://www.npmjs.com/package/@canonical/global-nav but do not have permissions to deprecate the old version. @barrymcgee can you handle that plz.

**Comment by barrymcgee** [comment]
<img width="1261" alt="screenshot 2019-03-08 at 11 04 05" src="https://user-images.githubusercontent.com/505570/54025278-f6e86700-4191-11e9-848f-0fde79cac3c5.png">
